### ISSUE TITLE
Zooming FATAL EXCEPTION

### ISSUE THREAD

**Issue by bierzorutas** [VEINHORN/ScrollGalleryView#13]
Error detail after zooming in a image several times:
09-13 12:05:38.403    5340-5340/XXXXX E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: xxxxxxxxxy, PID: 5340
    java.lang.IllegalArgumentException: pointerIndex out of range
            at android.view.MotionEvent.nativeGetAxisValue(Native Method)
            at android.view.MotionEvent.getX(MotionEvent.java:1983)
            at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
            at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
            at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
            at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1922)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2090)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2365)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1726)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2772)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2326)
            at android.view.View.dispatchPointerEvent(View.java:8687)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4485)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4343)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3884)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3937)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3903)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4013)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3911)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4070)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3884)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3937)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3903)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3911)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3884)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6300)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6256)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6209)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6462)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6421)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6493)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
            at android.view.Choreographer.doCallbacks(Choreographer.java:598)
            at android.view.Choreographer.doFrame(Choreographer.java:565)

**Comment by bierzorutas** [comment]
https://github.com/VEINHORN/ScrollGalleryView/pull/14
