### ISSUE TITLE
OutOfMemory exception

### ISSUE THREAD

**Issue by VEINHORN** [VEINHORN/ScrollGalleryView#31]
```
java.lang.OutOfMemoryError: Failed to allocate a 46656012 byte allocation with 16771776 free bytes and 31MB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
    at android.content.res.Resources.loadDrawable(Resources.java:2540)
    at android.content.res.Resources.getDrawable(Resources.java:806)
    at android.content.res.Resources.getDrawable(Resources.java:771)
    at com.veinhorn.scrollgalleryview.loader.DefaultImageLoader.loadBitmap(DefaultImageLoader.java:48)
    at com.veinhorn.scrollgalleryview.loader.DefaultImageLoader.loadThumbnail(DefaultImageLoader.java:39)
    at com.veinhorn.scrollgalleryview.ScrollGalleryView.addMedia(ScrollGalleryView.java:101)
    at com.veinhorn.scrollgalleryview.ScrollGalleryView.addMedia(ScrollGalleryView.java:89)
    at com.veinhorn.example.MainActivity.onCreate(MainActivity.java:56)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
    at android.app.ActivityThread.-wrap15(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by VEINHORN** [comment]
`java.lang.OutOfMemoryError: Failed to allocate a 46656012 byte allocation with 16771776 free bytes and 31MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at android.content.res.Resources.getDrawable(Resources.java:806)
	at android.content.res.Resources.getDrawable(Resources.java:771)
	at com.veinhorn.scrollgalleryview.loader.DefaultImageLoader.loadBitmap(DefaultImageLoader.java:48)
	at com.veinhorn.scrollgalleryview.loader.DefaultImageLoader.loadThumbnail(DefaultImageLoader.java:39)
	at com.veinhorn.scrollgalleryview.ScrollGalleryView.addMedia(ScrollGalleryView.java:101)
	at com.veinhorn.scrollgalleryview.ScrollGalleryView.addMedia(ScrollGalleryView.java:89)
	at com.veinhorn.example.MainActivity.onCreate(MainActivity.java:56)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by stefanopassador** [comment]
Same here!

**Comment by MinionAttack** [comment]
I have the same issue!

**Comment by madhacked** [comment]
Take a look here: https://developer.android.com/training/displaying-bitmaps/load-bitmap.html

If those tips don't work, try using a custom image loader like in the author's example here:

https://github.com/VEINHORN/ScrollGalleryView/blob/master/app/src/main/java/com/veinhorn/example/PicassoImageLoader.java

**Comment by VEINHORN** [comment]
I recommend to use custom [MediaLoader](https://github.com/VEINHORN/ScrollGalleryView/blob/master/library/src/main/java/com/veinhorn/scrollgalleryview/loader/MediaLoader.java) for image loading. For now [picasso-loader]() is available. I'm going to add more loaders soon (for Glide and Fresco).
