### ISSUE TITLE
Error scrollGalleryView.setOnScrollChangeListener

### ISSUE THREAD

**Issue by firestork** [VEINHORN/ScrollGalleryView#32]
I got error when I add this code :(

```java
 scrollGalleryView.setOnScrollChangeListener(new OnScrollChangeListener() {
  @Override
  public void onScrollChange(View v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {

  }
 });
```

**Comment by VEINHORN** [comment]
@firestork Hi. Can you please provide more information about this error?

**Comment by firestork** [comment]
Hi @VEINHORN  
I declare a scrollGalleryView in a fragmentactivity. show list image in my arraylist - > ok well
then I want get position when srcoll image.  here my full code

`public class Gallery2Activity extends FragmentActivity {

    private int pos;
    private ArrayList<CarImage> listCarImage = new ArrayList<>();
    private TextView textGallery;
    private ScrollGalleryView scrollGalleryView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_gallery2);

        Intent intent = getIntent();
        listCarImage = (ArrayList<CarImage>) intent
                .getSerializableExtra("listcar");

        pos = intent.getIntExtra("pos", -1);

        textGallery = (TextView) findViewById(R.id.textGallery);
        List<MediaInfo> infos = new ArrayList<>(listCarImage.size());
        //for (String url : images) infos.add(MediaInfo.mediaLoader(new PicassoImageLoader(url)));

        for (CarImage car : listCarImage) {
            infos.add(MediaInfo.mediaLoader(new PicassoImageLoader(getString(R.string.url_image) + car.getImage())));
        }
        scrollGalleryView = (ScrollGalleryView) findViewById(R.id.scroll_gallery_view);
        scrollGalleryView
                .setThumbnailSize(100)
                .setZoom(true)
                .setFragmentManager(getSupportFragmentManager())
                .addMedia(infos);
        if (pos != -1) {
            scrollGalleryView.setCurrentItem(pos);
        }
       scrollGalleryView.setOnScrollChangeListener(new OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {

            }
        });
    }

    private Bitmap toBitmap(int image) {
        return ((BitmapDrawable) getResources().getDrawable(image)).getBitmap();
    }
}`


and i got error 

> 
04-05 14:18:13.791 1455-1455/com.vcomsat.gsht E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.vcomsat.gsht, PID: 1455
                                                                java.lang.NoClassDefFoundError: com.vcomsat.gsht.activitys.Gallery2Activity$1
                                                                    at com.vcomsat.gsht.activitys.Gallery2Activity.onCreate(Gallery2Activity.java:55)
                                                                    at android.app.Activity.performCreate(Activity.java)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                                                    at android.os.Handler.dispatchMessage(Handler.java)
                                                                    at android.os.Looper.loop(Looper.java)
                                                                    at android.app.ActivityThread.main(ActivityThread.java)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
>

**Comment by firestork** [comment]
import android.view.View.OnScrollChangeListener;

**Comment by VEINHORN** [comment]
@firestork View.OnScrollChangeListener added in API level 23. Maybe you trying to run this code on an older API levels and it cannot find such class.

**Comment by firestork** [comment]
@VEINHORN  have any other way to get position when scroll?

**Comment by firestork** [comment]
@VEINHORN 
have no method addOnPageChangeListener in version  1.0.5. can u check this :dancers:

**Comment by voghDev** [comment]
+1. Would be really good to have a Listener to notify when pages are scrolled

Or alternatively, a `getCurrentItem()` method that lets you consult current page

**Comment by VEINHORN** [comment]
@voghDev thank you for your feedback. It would be nice if you provide PR.
