### ISSUE TITLE
ScrollGallery as a popup??

### ISSUE THREAD

**Issue by noxevolution** [VEINHORN/ScrollGalleryView#38]
Hi, I want to open this scroll gallery on a popup dialog but i am getting this error:

07-13 17:48:04.748 25834-25834/com.veinhorn.scrollgalleryview E/AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x7f0c005f (com.veinhorn.scrollgalleryview:id/viewPager) for fragment ImageFragment{422ca0b0 #0 id=0x7f0c005f}

**Comment by VEINHORN** [comment]
@noxevolution Hi! Can you please provide more detailed stacktrace?

**Comment by noxevolution** [comment]
@VEINHORN Hi! This is the full stacktrace:

```
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime: FATAL EXCEPTION: main
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime: Process: com.veinhorn.scrollgalleryview, PID: 2101
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x7f0c005f (com.veinhorn.scrollgalleryview:id/viewPager) for fragment ImageFragment{f6900c3 #0 id=0x7f0c005f}
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1059)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1111)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:631)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.View.measure(View.java:20151)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1524)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:695)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:631)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:158)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7225)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-14 00:53:30.680 2101-2101/com.veinhorn.scrollgalleryview E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by appach22** [comment]
@VEINHORN here is possible solution:
https://stackoverflow.com/questions/19888539/illegalargumentexception-no-view-found-for-id-for-fragment-viewpager-in-vie
