### ISSUE TITLE
java.io.FileNotFoundException: No content provider

### ISSUE THREAD

**Issue by VEINHORN** [VEINHORN/ScrollGalleryView#39]
08-08 21:18:57.663 26869-26869/com.veinhorn.scrollgalleryview D/MediaPlayer: setDataSource IOException happend : 
                                                                             java.io.FileNotFoundException: No content provider: http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4
                                                                                 at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1117)
                                                                                 at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:970)
                                                                                 at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:897)
                                                                                 at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1109)
                                                                                 at android.widget.VideoView.openVideo(VideoView.java:376)
                                                                                 at android.widget.VideoView.access$2100(VideoView.java:73)
                                                                                 at android.widget.VideoView$7.surfaceCreated(VideoView.java:657)
                                                                                 at android.view.SurfaceView.updateWindow(SurfaceView.java:714)
                                                                                 at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
                                                                                 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2327)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7062)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:576)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6917)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by pavanchilukuri** [comment]
Did you get an answer ? I'm stuck here. Would it be possible to view my [post ](https://stackoverflow.com/q/44447813/7004388)here once so that I can figure it out. Can you please guide me?
