### ISSUE TITLE
Crashes with latest Picasso added in the project

### ISSUE THREAD

**Issue by tfKamran** [VEINHORN/ScrollGalleryView#95]
Code copied from README.md:

    ScrollGalleryView
        .from(binding.scrollGalleryView)
        .settings(
            GallerySettings
                .from(childFragmentManager)
                .thumbnailSize(100)
                .enableZoom(true)
                .build()
        )
        .add( image(imageUrl))
        .build()

This is the crash log I get:

    java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class 
    Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in 
    /data/app/in.doma.channelpartner-njuQLWJ7OnSU6M5dJvb_pw==/base.apk)
            at com.veinhorn.scrollgalleryview.loader.picasso.PicassoImageLoader.loadThumbnail(PicassoImageLoader.java:44)
            at com.veinhorn.scrollgalleryview.ScrollGalleryView.addMedia(ScrollGalleryView.java:197)
            at com.veinhorn.scrollgalleryview.builder.GalleryBuilderImpl.build(GalleryBuilderImpl.java:63)
            
Picasso in my project:

    com.squareup.picasso:picasso:2.71828

**Comment by jc-yoonet** [comment]
You can use these to your app.gradle

```
implementation 'com.squareup.picasso:picasso:2.5.2'
implementation 'com.veinhorn.scrollgalleryview:library:1.2.6'
implementation 'com.veinhorn.scrollgalleryview:picasso-loader:1.2.0'
```
